version: '3.1'
services:
  # Java Backend service
  backend:
    build:
      context: ./LogInApp
      dockerfile: Dockerfile
      target: final
    ports:
      - 5232:5232
  
  # React Frontend service
  frontend:
    build:
      context: ./login-app-front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend