name: OWASP ZAP scanning
on:
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Compose
        run: |
          docker-compose up -d
      - name: Start OWASP ZAP scan
        run: | 
          chmod 777 ${PWD}
          docker run --rm -v ${PWD}:/zap/wrk/:rw --name owasp -dt zaproxy/zap-stable /bin/bash
          docker exec owasp zap-baseline.py -t http://localhost:3000 -I -j --auto -r DAST_Report.html
      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: DAST_Report.html
