name: OWASP ZAP scanning
on:
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Remove Previous Docker Compose Builds
        run: |
          docker-compose down --rmi all --volumes --remove-orphans

      - name: Build Docker Compose
        run: |
          docker-compose up -d
      - name: Start OWASP ZAP scan
        run: | 
          chmod -R u+rw ${PWD}
          docker run -v ${PWD}:/zap/wrk:rw --user root --network="host" zaproxy/zap-stable zap-baseline.py -t http://localhost:3000 -I -r scan-report.html
      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: scan-report.html
